name: Actions Workflow

on: [push]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Simple JavaScript Actions
        id: greet
        uses: https://github.com/lambatea/helloworld-javascript-actions@master
        with:
          who-to-greet: Anuja
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
